### ISSUE TITLE
Minor issue with the README file

### ISSUE THREAD

**Issue by NoGoat** [defname/rofi-iwd-wifi-menu#1]
In the README file, it asks you to run using 
```
rofi -show WiFI -modi "WiFi:./iwdrofimenu.py"
```
The word WiFi is spelled incorrectly with a capital I instead of a small I, which prevents the program from executing.

So, the command should be,
```
rofi -show WiFi -modi "WiFi:./iwdrofimenu.py"
```

**Comment by defname** [comment]
Thanks for the hint, I corrected it
