### ISSUE TITLE
no icons

### ISSUE THREAD

**Issue by vykng** [defname/rofi-iwd-wifi-menu#3]
Can't seem to get the icons shown in the example to appear using the default settings.  Everything else appears to work fine. What would be the best way to debug this. Thanks.

**Comment by defname** [comment]
If icons are shown depends on your rofi configuration.
You can try
```
rofi -show wifi -modi wifi:iwdrofimenu -no-config -show-icons
```
then you should see the default rofi theme but with icons.
If it's working it's just the configuration of your rofi theme.

**Comment by vykng** [comment]
That did it. Appreciate your help.
