### ISSUE TITLE
TypeError: must be str, not NoneType

### ISSUE THREAD

**Issue by Dutt-A** [defname/rofi-iwd-wifi-menu#6]
```
$ rofi -show wifi -modi "wifi:./iwdrofimenu.py"
Traceback (most recent call last):
  File "/home/aakash/Downloads/rofi-iwd-wifi-menu/./iwdrofimenu.py", line 85, in <module>
    iwdrofimenu.Main(DEVICE, args)
  File "/home/aakash/Downloads/rofi-iwd-wifi-menu/iwdrofimenu/main.py", line 73, in __init__
    if self.wifi_is_blocked():
       ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aakash/Downloads/rofi-iwd-wifi-menu/iwdrofimenu/main.py", line 144, in wifi_is_blocked
    if line.find(self.iwd.adapter()) != -1:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: must be str, not NoneType
```

**Comment by benmanone** [comment]
Same here

**Comment by oskhen** [comment]
Also having this issue

**Comment by prologen** [comment]
> Note: As of version 1.23, only root and members of the netdev or the wheel user group are allowed to interact with iwd. In order to use iwctl, you need to add your user to one of those groups.

Source: https://bbs.archlinux.org/viewtopic.php?pid=2019079#p2019079

Would not recommend adding user to 'wheel' for security reasons. Netdev is debian-specific, e.g for arch the relevant group is "network".

As such,
Adding user to 'network' user group 
`sudo usermod -a -G network <user>`

Fixed the issue.

**Comment by defname** [comment]
I added an error message that might give some hints and updated the README.

Thanks a lot to @oskhen, I would never have been able to reproduce the error myself
